id: c156dbef2db84a488cd909ea0827ed35
initial_creation_type: ocr
source_metadata:
  volumes:
    3c04735f47db45d1848acb8a520de501:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
